update

diff --git a/stow/bin/.config/bin/bl b/stow/bin/.config/bin/bl
--- a/stow/bin/.config/bin/bl
+++ b/stow/bin/.config/bin/bl
@@ -21,9 +21,9 @@ else
     exit 1
 fi
 
-if gum spin --spinner globe --show-error --title "Logging into bloccdev registry" -- az acr login -n bloccdev --subscription 5b37ef96-b4b4-483f-9955-92f7a3e74ee1; then
-    echo "✅ Logged into bloccdev registry"
-else
-    echo "❌ Failed to log into bloccdev registry"
-    exit 1
-fi
+# if gum spin --spinner globe --show-error --title "Logging into bloccdev registry" -- az acr login -n bloccdev --subscription 5b37ef96-b4b4-483f-9955-92f7a3e74ee1; then
+#     echo "✅ Logged into bloccdev registry"
+# else
+#     echo "❌ Failed to log into bloccdev registry"
+#     exit 1
+# fi
